# Generated by Django 3.0.5 on 2023-07-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_question_qtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='audio',
        ),
        migrations.AddField(
            model_name='course',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
