# Generated by Django 3.0.5 on 2023-07-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20230705_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='blankans',
            field=models.TextField(blank=True, null=True),
        ),
    ]
