# Generated by Django 3.0.5 on 2023-07-07 16:04

from django.db import migrations, models
import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_question_blankans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=exam.models.get_audio_upload_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='blankans',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
