# Generated by Django 3.0.5 on 2023-07-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20230711_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='blankans',
        ),
    ]
