# Generated by Django 3.0.5 on 2023-07-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_remove_question_blankans'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='blankans',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
