# Generated by Django 3.0.5 on 2023-07-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_question_blankans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='blankans',
            field=models.CharField(blank=True, choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], max_length=100, null=True),
        ),
    ]
