# Generated by Django 3.0.5 on 2023-07-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20230712_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='blankans',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
