# Generated by Django 3.0.5 on 2023-07-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20230712_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='timer',
            field=models.IntegerField(blank=True, choices=[(30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes'), (90, '90 minutes')], null=True),
        ),
    ]
