# Generated by Django 3.0.5 on 2023-07-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_course_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='blankans',
        ),
    ]
