# Generated by Django 3.0.5 on 2023-08-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_auto_20230726_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='decision_making_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='emotional_intelligence_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
