# Generated by Django 3.0.5 on 2023-08-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_auto_20230824_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='comprehension_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtag',
            field=models.CharField(blank=True, choices=[('Comprehension', 'Comprehension'), ('Decision-making', 'Decision-making'), ('Emotional Intelligence', 'Emotional Intelligence')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ComprehensionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Question')),
            ],
        ),
    ]
